### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by Gregouille** [LaboratoireMecaniqueLille/crappy#1]
Yo,
ce serait possible d'avoir un gros .exe qui fait toute l'install et une interface graphique comme dans Labview ?

Just kidding.

**Comment by CMartelLML** [comment]
Dear customer,

I am deeply sorry for your inconvenience, but unfortunately the feature your requested is not part of our on-going development plan for the time being.

Kind regards,
Corentin Martel
Lead Developer at Crappy
